languageCode: "en-gb"
uglyURLs: false
title: "COAR Notify Documentation"
theme: "coar_notify"
enableRobotsTXT: true
#disableKinds: ["RSS","taxonomy","taxonomyTerm"]
disableKinds: [ "RSS" ]
metaDataFormat: "yaml"
enableGitInfo: false
blackfriday:
  smartypants: false
  smartDashes: false
  extensionsmask: [ "autolink" ] #disables these extensions
disablePathToLower: true
taxonomies:
  tag: "tags"
  status: "status"
outputs:
  page: [ html,json ]

#outputFormats:
#  JsonLdFormat:
#    baseName: index
#    isPlainText: false
#    mediaType: application/ld+json



params:
  contexts:
    notify:
      name: "Notify"
      uri: "http://purl.org/coar/notify"
    as2:
      name: "Activity Streams 2.0"
      uri: "https://www.w3.org/ns/activitystreams"
  actors:
    generic-actor:
      "id": "https://orcid.org/0000-0002-1825-0097"
      name: "Josiah Carberry"
      "type": [ "Person" ]
      "ldp:inbox": "https://josiahcarberry.com/ldn/inbox"
    author:
      "id": "https://orcid.org/0000-0002-1825-0097"
      name: "Josiah Carberry"
      "type": [ "Person" ]
      "ldp:inbox": "https://josiahcarberry.com/ldn/inbox"
    reviewer:
      "id": "https://isni.org/isni/0000000122832703"
      name: "H G Wells"
      "type": [ "Person" ]
      "ldp:inbox": "https://hgwells.com/ldn/inbox"
  systems:
    generic-origin-system:
      "id": "https://origin-system.org"
      "type": [ "Service" ]
      "ldp:inbox": "https://origin-system.org/inbox/"
    generic-target-system:
      "id": "https://target-system.org"
      "type": [ "Service" ]
      "ldp:inbox": "https://target-system.org/inbox/"
    repository:
      "id": "https://repository.org"
      "type": [ "Service" ]
      "ldp:inbox": "https://repository.org/inbox/"
    review-service:
      "id": "https://reviewservice.org"
      "type": [ "Service" ]
      "ldp:inbox": "https://reviewservice.org/requests/inbox/"
    overlay-journal:
      "id": "https://overlay-journal.org"
      "type": [ "Service" ]
      "ldp:inbox": "https://overlay-journal.org/requests/inbox/"
    aggregation-service:
      "id": "https://aggregator-service.org"
      "type": [ "Service" ]
      "ldp:inbox": "https://aggregator-service.org/requests/inbox/"
  objects:
    generic-object:
      "id": "https://origin-system.org/resources/0021"
      "type": [ "Document" ]
      "ietf:cite-as": "https://doi.org/10.4598/12123487"
    generic-object-in-reply-to:
      "id": "https://target-system.org/resources/0044"
      "type": [ "Document" ]
      "ietf:cite-as": "https://doi.org/10.1224/0983657"
    preprint:
      "id": "https://repository.org/preprint/201203/421/"
      "type": [ "sorg:AboutPage" ]
      "ietf:cite-as": "https://doi.org/10.5555/12345680"
      url:
        "id": "https://repository.org/preprint/201203/421/content.pdf"
        "type": [ "Article","sorg:ScholarlyArticle" ]
        "media-type": "application/pdf"
    submission:
      "id": "https://overlay-journal.org/submissions/00001/"
      "type": [ "sorg:AboutPage" ]
      url:
        "id": "https://overlay-journal.org/submissions/00001/files/content.pdf"
        "type": [ "Article","sorg:ScholarlyArticle" ]
        "media-type": "application/pdf"
    review:
      "id": "https://reviewservice.org/review/geo/202103/0021"
      "type": [ "Document","sorg:Review" ]
      "ietf:cite-as": "https://doi.org/10.3214/987654"
      "coar-notify:reviews":
        object:
          "id": "https://repository.org/preprint/201203/421/"
          "ietf:cite-as": "https://doi.org/10.5555/12345680"
    "journal-review":
      "id": "https://overlay-journal.org/reviews/000001/00001"
      "type": [ "Document","sorg:Review" ]
      "ietf:cite-as": "https://doi.org/10.3214/987654"
      "coar-notify:reviews":
        object:
          "id": "https://repository.org/preprint/201203/421/"
          "ietf:cite-as": "https://doi.org/10.5555/12345680"
    "repository-review":
      "id": "https://repository.org/review/00001"
      "type": [ "Document","sorg:Review" ]
      "ietf:cite-as": "https://doi.org/10.3214/000001"
      "coar-notify:reviews":
        object:
          "id": "https://repository.org/preprint/201203/421/"
          "ietf:cite-as": "https://doi.org/10.5555/12345680"
    endorsement:
      "id": "https://overlay-journal.org/articles/00001/"
      "type": [ "Page","sorg:WebPage" ]
      "ietf:cite-as": "https://overlay-journal.org/articles/00001/"
      "coar-notify:endorses":
        object:
          "id": "https://repository.org/preprint/201203/421/"
          "ietf:cite-as": "https://doi.org/10.5555/12345680"
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4